version: "3.9"

services:
  app:
    build:
      context: .
      args:
        USERNAME: ${USERNAME}
    ports:
      - "8000:8000"
    volumes:
      - ./django_app:/django_app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
